import fs from 'fs-extra';
import path from 'path';
import chalk from 'chalk';
import ora from 'ora';
import inquirer from 'inquirer';

export async function initCommand(name?: string, options?: any) {
  const spinner = ora();

  try {
    if (!name) {
      const answers = await inquirer.prompt([
        {
          type: 'input',
          name: 'projectName',
          message: 'What is your agent name?',
          default: 'my-agent',
        },
      ]);
      name = answers.projectName;
    }

    const projectPath = path.join(process.cwd(), name!);

    if (await fs.pathExists(projectPath)) {
      console.log(chalk.red(`✗ Directory ${name} already exists`));
      process.exit(1);
    }

    spinner.start('Creating agent project...');

    await fs.ensureDir(projectPath);
    await fs.ensureDir(path.join(projectPath, 'config'));
    await fs.ensureDir(path.join(projectPath, 'tools'));
    await fs.ensureDir(path.join(projectPath, 'workflows'));

    // Determine template tools based on options
    const template = options?.template || 'assistant';
    let defaultTools = ['bash', 'file-ops', 'http', 'json', 'text'];
    let instructions = `You are ${name}, an AI agent designed to help with tasks.`;

    if (template === 'chatbot') {
      defaultTools = ['http', 'json', 'text', 'datetime'];
      instructions = `You are ${name}, a helpful AI chatbot. Answer questions clearly and helpfully.`;
    } else if (template === 'researcher') {
      defaultTools = ['http', 'web-scraper', 'json', 'text', 'file-ops'];
      instructions = `You are ${name}, a research assistant. Help users find and analyze information from various sources.`;
    } else if (template === 'developer') {
      defaultTools = ['bash', 'python', 'file-ops', 'github', 'json'];
      instructions = `You are ${name}, a coding assistant. Help with code generation, debugging, and technical tasks.`;
    } else if (template === 'analyst') {
      defaultTools = ['csv', 'json', 'database', 'http', 'text'];
      instructions = `You are ${name}, a data analyst. Help analyze data and generate insights.`;
    }

    const agentConfig = {
      name: name,
      version: '1.0.0',
      description: `${name} AI agent`,
      template: template,
      capabilities: ['chat', 'task-execution', 'tool-use'],
      tools: defaultTools,
      instructions: instructions,
      ai: {
        provider: options?.aiProvider || 'none',
        model: 'gpt-3.5-turbo',
        temperature: 0.7,
        maxTokens: 4000
      },
      mcp: {
        servers: []
      },
      environment: {
        nodeEnv: 'development',
        port: 3000
      },
    };

    await fs.writeJson(
      path.join(projectPath, 'config', 'agent.json'),
      agentConfig,
      { spaces: 2 }
    );

    // Create main agent file
    const agentCode = `// ${name} - AI Agent
// Generated by stick.ai CLI

const { ${agentConfig.ai.provider !== 'none' ? 'IntelligentAgent' : 'Agent'} } = require('@stick-ai/runtime');

const config = require('./config/agent.json');

async function main() {
  ${agentConfig.ai.provider !== 'none' ? `
  // Create intelligent agent with ${agentConfig.ai.provider}
  const agent = new IntelligentAgent(
    config,
    {
      provider: '${agentConfig.ai.provider}',
      apiKey: process.env.${agentConfig.ai.provider.toUpperCase()}_API_KEY,
      model: '${agentConfig.ai.model}',
      temperature: ${agentConfig.ai.temperature},
      maxTokens: ${agentConfig.ai.maxTokens}
    }
  );
  ` : `
  // Create basic agent (no AI provider)
  const agent = new Agent(config);
  `}
  
  console.log('🤖 ${name} is running...');
  console.log('Tools:', config.tools.join(', '));
  
  // Example: Run agent with input
  // const result = await agent.run('Your task here');
  // console.log('Result:', result);
}

if (require.main === module) {
  main().catch(console.error);
}

module.exports = { main };
`;

    await fs.writeFile(path.join(projectPath, 'index.js'), agentCode);

    // Create package.json
    const packageJson = {
      name: name,
      version: '1.0.0',
      description: agentConfig.description,
      main: 'index.js',
      scripts: {
        start: 'node index.js',
        dev: 'nodemon index.js'
      },
      dependencies: {
        '@stick-ai/runtime': '^1.1.0'
      },
      devDependencies: {
        'nodemon': '^3.0.0'
      }
    };

    await fs.writeJson(path.join(projectPath, 'package.json'), packageJson, { spaces: 2 });

    const readme = `# ${name}

AI Agent powered by stick.ai

## Getting Started

\`\`\`bash
cd ${name}
stick deploy
stick run ${name}
\`\`\`

## Configuration

Edit \`config/agent.json\` to customize your agent's behavior.
`;

    await fs.writeFile(path.join(projectPath, 'README.md'), readme);

    const gitignore = `node_modules/
dist/
.env
.env.local
*.log
.DS_Store
`;

    await fs.writeFile(path.join(projectPath, '.gitignore'), gitignore);

    const envExample = `# Agent Configuration
AGENT_NAME=${name}
AGENT_PORT=3000
`;

    await fs.writeFile(path.join(projectPath, '.env.example'), envExample);

    spinner.succeed(chalk.green(`✓ Agent project "${name}" created successfully`));

    console.log('\n' + chalk.bold('Next steps:'));
    console.log(chalk.cyan(`  cd ${name}`));
    console.log(chalk.cyan('  stick deploy'));
    console.log(chalk.cyan('  stick run ' + name));
    console.log('\n' + chalk.dim('Learn more: https://stick.ai/docs'));
  } catch (error) {
    spinner.fail(chalk.red('✗ Failed to create agent project'));
    console.error(error);
    process.exit(1);
  }
}
