"""Prometheus metrics — instrumentation for all MemoraForge services.

Exposes:
- Request counters and latency histograms per service
- Memory hub retrieval performance
- Context stream utilization
- Cache hit/miss rates
- Active agent/connection gauges
"""

from __future__ import annotations

import time
from functools import wraps
from typing import Any, Callable

from prometheus_client import (
    Counter, Gauge, Histogram, Info,
    generate_latest, CONTENT_TYPE_LATEST,
)
from fastapi import FastAPI, Request, Response
from starlette.middleware.base import BaseHTTPMiddleware

# ─── Service info ────────────────────────────────────────────────

SERVICE_INFO = Info("memoraforge_service", "Service metadata")

# ─── Request metrics ────────────────────────────────────────────

REQUEST_COUNT = Counter(
    "memoraforge_requests_total",
    "Total HTTP requests",
    ["service", "method", "endpoint", "status"],
)

REQUEST_LATENCY = Histogram(
    "memoraforge_request_duration_seconds",
    "Request latency in seconds",
    ["service", "endpoint"],
    buckets=[0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0],
)

# ─── Memory Hub metrics ─────────────────────────────────────────

RETRIEVAL_LATENCY = Histogram(
    "memoraforge_retrieval_duration_seconds",
    "Memory retrieval latency",
    ["source"],  # vector_store, knowledge_graph, full_text, combined
    buckets=[0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0],
)

RETRIEVAL_RESULTS = Histogram(
    "memoraforge_retrieval_results_count",
    "Number of results returned per retrieval",
    ["source"],
    buckets=[1, 5, 10, 25, 50, 100, 250],
)

MEMORIES_STORED = Counter(
    "memoraforge_memories_stored_total",
    "Total memories stored",
    ["memory_type"],
)

MEMORIES_EVICTED = Counter(
    "memoraforge_memories_evicted_total",
    "Total memories evicted",
    ["reason"],  # lru, ttl, relevance
)

TOTAL_TOKENS_STORED = Gauge(
    "memoraforge_tokens_stored",
    "Total tokens currently in memory hub",
)

# ─── MCP metrics ─────────────────────────────────────────────────

CONTEXT_STREAMS = Gauge(
    "memoraforge_context_streams_active",
    "Active context streams",
)

CONTEXT_STREAM_TOKENS = Gauge(
    "memoraforge_context_stream_tokens",
    "Total tokens across all streams",
)

CONTEXT_PUSHES = Counter(
    "memoraforge_context_pushes_total",
    "Total context push operations",
)

CONTEXT_RETRIEVALS = Counter(
    "memoraforge_context_retrievals_total",
    "Total context retrieval operations",
)

COMPRESSION_RATIO = Histogram(
    "memoraforge_compression_ratio",
    "LZ4 compression ratio",
    buckets=[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0],
)

# ─── ACP metrics ─────────────────────────────────────────────────

AGENTS_REGISTERED = Gauge(
    "memoraforge_agents_registered",
    "Total registered agents",
)

AGENTS_CONNECTED = Gauge(
    "memoraforge_agents_connected",
    "Currently connected agents (WebSocket)",
)

RPC_CALLS = Counter(
    "memoraforge_rpc_calls_total",
    "Total RPC method calls",
    ["method", "status"],
)

RATE_LIMIT_HITS = Counter(
    "memoraforge_rate_limit_hits_total",
    "Total rate limit rejections",
)

# ─── Cache metrics ───────────────────────────────────────────────

CACHE_HITS = Counter(
    "memoraforge_cache_hits_total",
    "Cache hit count",
    ["cache_layer"],  # redis, local
)

CACHE_MISSES = Counter(
    "memoraforge_cache_misses_total",
    "Cache miss count",
    ["cache_layer"],
)

# ─── LLM metrics ────────────────────────────────────────────────

LLM_REQUESTS = Counter(
    "memoraforge_llm_requests_total",
    "Total LLM inference requests",
    ["model", "status"],
)

LLM_LATENCY = Histogram(
    "memoraforge_llm_duration_seconds",
    "LLM inference latency",
    ["model"],
    buckets=[0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0, 30.0, 60.0],
)

LLM_TOKENS_GENERATED = Counter(
    "memoraforge_llm_tokens_generated_total",
    "Total tokens generated by LLM",
    ["model"],
)


# ─── Middleware ──────────────────────────────────────────────────


class PrometheusMiddleware(BaseHTTPMiddleware):
    """FastAPI middleware for automatic request instrumentation."""

    def __init__(self, app: FastAPI, service_name: str):
        super().__init__(app)
        self.service_name = service_name
        SERVICE_INFO.info({"service": service_name, "version": "0.1.0"})

    async def dispatch(self, request: Request, call_next):
        start = time.time()
        response = None
        try:
            response = await call_next(request)
            return response
        finally:
            elapsed = time.time() - start
            status = str(response.status_code) if response else "500"
            endpoint = request.url.path

            REQUEST_COUNT.labels(
                service=self.service_name,
                method=request.method,
                endpoint=endpoint,
                status=status,
            ).inc()

            REQUEST_LATENCY.labels(
                service=self.service_name,
                endpoint=endpoint,
            ).observe(elapsed)


def setup_metrics(app: FastAPI, service_name: str):
    """Add Prometheus metrics middleware and /metrics endpoint to a FastAPI app."""
    app.add_middleware(PrometheusMiddleware, service_name=service_name)

    @app.get("/metrics", include_in_schema=False)
    async def metrics():
        return Response(
            content=generate_latest(),
            media_type=CONTENT_TYPE_LATEST,
        )


# ─── Decorator for timing functions ─────────────────────────────


def track_latency(histogram: Histogram, **labels):
    """Decorator to track function execution time in a Prometheus histogram."""
    def decorator(func: Callable):
        @wraps(func)
        async def wrapper(*args, **kwargs):
            start = time.time()
            try:
                return await func(*args, **kwargs)
            finally:
                histogram.labels(**labels).observe(time.time() - start)
        return wrapper
    return decorator
