// my-agbrute4ent - AI Agent
// Generated by stick.ai CLI

const { Agent } = require('@stick-ai/runtime');

const config = require('./config/agent.json');

async function main() {
  
  // Create basic agent (no AI provider)
  const agent = new Agent(config);
  
  
  console.log('🤖 my-agbrute4ent is running...');
  console.log('Tools:', config.tools.join(', '));
  
  // Example: Run agent with input
  // const result = await agent.run('Your task here');
  // console.log('Result:', result);
}

if (require.main === module) {
  main().catch(console.error);
}

module.exports = { main };
