'use client';

import { Terminal, Bot, Search, Code, BarChart, MessageSquare, Copy, Check } from 'lucide-react';
import Link from 'next/link';
import { useState } from 'react';

const examples = [
  {
    name: 'Simple Chatbot',
    description: 'A conversational AI agent using OpenAI',
    icon: MessageSquare,
    template: 'chatbot',
    code: `// Generated by: stick init chatbot --template chatbot --ai openai

const { IntelligentAgent } = require('@stick-ai/runtime');

const agent = new IntelligentAgent({
  name: 'chatbot',
  template: 'chatbot',
  tools: ['text', 'datetime'],
  instructions: 'You are a friendly chatbot...'
}, {
  provider: 'openai',
  model: 'gpt-3.5-turbo'
});

agent.start();`
  },
  {
    name: 'Web Researcher',
    description: 'Research assistant with web scraping',
    icon: Search,
    template: 'researcher',
    code: `// Generated by: stick init researcher --template researcher

const { IntelligentAgent } = require('@stick-ai/runtime');

const agent = new IntelligentAgent({
  name: 'researcher',
  template: 'researcher',
  tools: ['http', 'web-scraper', 'json', 'text'],
  instructions: 'You are a research assistant...'
}, {
  provider: 'anthropic',
  model: 'claude-3-sonnet'
});

agent.start();`
  },
  {
    name: 'Code Assistant',
    description: 'Developer agent with file operations',
    icon: Code,
    template: 'developer',
    code: `// Generated by: stick init dev-assistant --template developer

const { IntelligentAgent } = require('@stick-ai/runtime');

const agent = new IntelligentAgent({
  name: 'dev-assistant',
  template: 'developer',
  tools: ['bash', 'file-ops', 'github', 'json'],
  instructions: 'You are a developer assistant...'
}, {
  provider: 'openai',
  model: 'gpt-4'
});

agent.start();`
  },
  {
    name: 'Data Analyst',
    description: 'Analyze data with SQL and CSV tools',
    icon: BarChart,
    template: 'analyst',
    code: `// Generated by: stick init analyst --template analyst

const { IntelligentAgent } = require('@stick-ai/runtime');

const agent = new IntelligentAgent({
  name: 'analyst',
  template: 'analyst',
  tools: ['database', 'csv', 'json', 'datetime'],
  instructions: 'You are a data analyst...'
}, {
  provider: 'openai',
  model: 'gpt-4'
});

agent.start();`
  }
];

export default function Examples() {
  const [copied, setCopied] = useState<number | null>(null);

  const copyCode = (code: string, index: number) => {
    navigator.clipboard.writeText(code);
    setCopied(index);
    setTimeout(() => setCopied(null), 2000);
  };

  return (
    <main className="min-h-screen bg-background text-foreground">
      <nav className="fixed top-0 w-full z-50 glass-morphic border-b border-border">
        <div className="max-w-7xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <Terminal className="w-6 h-6 text-accent-blue" />
            <span className="text-xl font-bold">stick.ai</span>
          </Link>
          <div className="flex items-center gap-6">
            <Link href="/docs" className="text-sm text-zinc-400 hover:text-white transition-colors">
              Docs
            </Link>
            <Link href="/examples" className="text-sm text-white font-semibold">
              Examples
            </Link>
          </div>
        </div>
      </nav>

      <div className="pt-24 pb-20">
        <div className="max-w-6xl mx-auto px-6">
          <div className="text-center mb-16">
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full glass-morphic text-sm text-zinc-400 mb-6">
              <Bot className="w-4 h-4 text-accent-blue" />
              Example Agents
            </div>
            <h1 className="text-5xl md:text-6xl font-bold mb-6">
              Agent <span className="gradient-text">Examples</span>
            </h1>
            <p className="text-xl text-zinc-400 max-w-2xl mx-auto">
              Copy-paste examples to get started quickly
            </p>
          </div>

          <div className="space-y-8">
            {examples.map((ex, i) => {
              const Icon = ex.icon;
              return (
                <div key={i} className="glass-morphic rounded-lg border border-border overflow-hidden">
                  <div className="p-6">
                    <div className="flex items-start gap-4 mb-4">
                      <div className="w-12 h-12 rounded-lg bg-accent-blue/20 flex items-center justify-center">
                        <Icon className="w-6 h-6 text-accent-blue" />
                      </div>
                      <div className="flex-1">
                        <h2 className="text-2xl font-bold mb-2">{ex.name}</h2>
                        <p className="text-zinc-400">{ex.description}</p>
                      </div>
                      <div className="px-3 py-1 rounded-full bg-surface/50 text-xs text-accent-cyan">
                        {ex.template}
                      </div>
                    </div>

                    <div className="relative group">
                      <button
                        onClick={() => copyCode(ex.code, i)}
                        className="absolute right-4 top-4 p-2 rounded-md bg-surface/80 hover:bg-surface opacity-0 group-hover:opacity-100 transition-all z-10"
                      >
                        {copied === i ? (
                          <Check className="w-4 h-4 text-green-500" />
                        ) : (
                          <Copy className="w-4 h-4 text-zinc-400" />
                        )}
                      </button>
                      <pre className="bg-surface/50 border border-border rounded-md p-4 overflow-x-auto text-sm">
                        <code className="text-zinc-300">{ex.code}</code>
                      </pre>
                    </div>

                    <div className="mt-4 flex gap-3">
                      <a
                        href={`https://github.com/astickleyid/agent-builder-framework/tree/main/examples/${ex.template}`}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-sm text-accent-blue hover:underline"
                      >
                        View Full Example →
                      </a>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>

          <div className="mt-16 text-center p-8 glass-morphic rounded-lg border border-accent-blue/20">
            <h3 className="text-2xl font-bold mb-4">Create Your Own Agent</h3>
            <p className="text-zinc-400 mb-6">
              Start building with the interactive CLI
            </p>
            <pre className="bg-surface/50 border border-border rounded-md p-4 mb-6 inline-block">
              <code className="text-accent-cyan">$ npm install -g @stick-ai/cli{'\n'}$ stick</code>
            </pre>
            <div className="flex gap-4 justify-center">
              <Link
                href="/docs/getting-started"
                className="px-6 py-3 bg-accent-blue hover:bg-accent-blue/90 text-white rounded-md font-semibold transition-all"
              >
                Get Started
              </Link>
              <Link
                href="/docs"
                className="px-6 py-3 glass-morphic hover:bg-surface text-white rounded-md font-semibold transition-all"
              >
                Read Docs
              </Link>
            </div>
          </div>
        </div>
      </div>
    </main>
  );
}
