'use client';

import { Terminal, Bot, Search, Code, BarChart, MessageSquare, Copy, Check, Sparkles } from 'lucide-react';
import Link from 'next/link';
import { useState } from 'react';

const examples = [
  {
    name: 'Simple Chatbot',
    description: 'A conversational AI agent using OpenAI',
    icon: MessageSquare,
    template: 'chatbot',
    code: `// Generated by: stick init chatbot --template chatbot --ai openai

const { IntelligentAgent } = require('@stick-ai/runtime');

const agent = new IntelligentAgent({
  name: 'chatbot',
  template: 'chatbot',
  tools: ['text', 'datetime'],
  instructions: 'You are a friendly chatbot...'
}, {
  provider: 'openai',
  model: 'gpt-3.5-turbo'
});

agent.start();`
  },
  {
    name: 'Web Researcher',
    description: 'Research assistant with web scraping',
    icon: Search,
    template: 'researcher',
    code: `// Generated by: stick init researcher --template researcher

const { IntelligentAgent } = require('@stick-ai/runtime');

const agent = new IntelligentAgent({
  name: 'researcher',
  template: 'researcher',
  tools: ['http', 'web-scraper', 'json', 'text'],
  instructions: 'You are a research assistant...'
}, {
  provider: 'anthropic',
  model: 'claude-3-sonnet'
});

agent.start();`
  },
  {
    name: 'Code Assistant',
    description: 'Developer agent with file operations',
    icon: Code,
    template: 'developer',
    code: `// Generated by: stick init dev-assistant --template developer

const { IntelligentAgent } = require('@stick-ai/runtime');

const agent = new IntelligentAgent({
  name: 'dev-assistant',
  template: 'developer',
  tools: ['bash', 'file-ops', 'github', 'json'],
  instructions: 'You are a developer assistant...'
}, {
  provider: 'openai',
  model: 'gpt-4'
});

agent.start();`
  },
  {
    name: 'Data Analyst',
    description: 'Analyze data with SQL and CSV tools',
    icon: BarChart,
    template: 'analyst',
    code: `// Generated by: stick init analyst --template analyst

const { IntelligentAgent } = require('@stick-ai/runtime');

const agent = new IntelligentAgent({
  name: 'analyst',
  template: 'analyst',
  tools: ['database', 'csv', 'json', 'datetime'],
  instructions: 'You are a data analyst...'
}, {
  provider: 'openai',
  model: 'gpt-4'
});

agent.start();`
  }
];

export default function Examples() {
  const [copied, setCopied] = useState<number | null>(null);

  const copyCode = (code: string, index: number) => {
    navigator.clipboard.writeText(code);
    setCopied(index);
    setTimeout(() => setCopied(null), 2000);
  };

  return (
    <main className="min-h-screen bg-background text-foreground">
      {/* Fixed Header */}
      <nav className="fixed top-0 w-full z-50 glass-morphic border-b border-border">
        <div className="max-w-7xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <div className="relative">
              <Terminal className="w-6 h-6 text-accent-blue" />
              <div className="absolute inset-0 blur-md bg-accent-blue/30" />
            </div>
            <span className="text-xl font-bold">stick.ai</span>
          </Link>
          <div className="flex items-center gap-6">
            <Link href="/docs" className="text-sm text-zinc-400 hover:text-white transition-colors">
              Docs
            </Link>
            <Link href="/examples" className="text-sm text-white font-semibold">
              Examples
            </Link>
            <Link href="/playground" className="text-sm text-zinc-400 hover:text-white transition-colors">
              Playground
            </Link>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <div className="pt-24 pb-8">
        <div className="max-w-6xl mx-auto px-6">
          <div className="text-center mb-12">
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full glass-morphic text-sm text-zinc-400 mb-6">
              <Bot className="w-4 h-4 text-accent-blue" />
              Production-Ready Examples
            </div>
            <h1 className="text-5xl md:text-6xl font-bold mb-4">
              Agent <span className="gradient-text">Templates</span>
            </h1>
            <p className="text-xl text-zinc-400 max-w-2xl mx-auto leading-relaxed">
              Production-ready agent templates to accelerate your development. Copy, customize, and deploy in minutes.
            </p>
          </div>

          <div className="space-y-6">
            {examples.map((ex, i) => {
              const Icon = ex.icon;
              return (
                <div key={i} className="holographic-card rounded-xl border border-border overflow-hidden">
                  <div className="p-6">
                    <div className="flex items-start gap-4 mb-4">
                      <div className="w-12 h-12 rounded-xl bg-accent-blue/20 flex items-center justify-center border border-accent-blue/30">
                        <Icon className="w-6 h-6 text-accent-blue" />
                      </div>
                      <div className="flex-1">
                        <h2 className="text-2xl font-bold mb-1">{ex.name}</h2>
                        <p className="text-zinc-400">{ex.description}</p>
                      </div>
                      <div className="px-3 py-1 rounded-full bg-accent-cyan/20 text-xs text-accent-cyan font-medium border border-accent-cyan/30">
                        {ex.template}
                      </div>
                    </div>

                    <div className="relative group">
                      <button
                        onClick={() => copyCode(ex.code, i)}
                        className="absolute right-4 top-4 p-2 rounded-lg bg-surface/80 hover:bg-surface border border-border opacity-0 group-hover:opacity-100 transition-all z-10"
                      >
                        {copied === i ? (
                          <Check className="w-4 h-4 text-accent-cyan" />
                        ) : (
                          <Copy className="w-4 h-4 text-zinc-400" />
                        )}
                      </button>
                      <pre className="bg-black/40 border border-border rounded-xl p-5 overflow-x-auto text-sm">
                        <code className="text-zinc-300 terminal-text">{ex.code}</code>
                      </pre>
                    </div>

                    <div className="mt-4 flex gap-3">
                      <a
                        href={`https://github.com/astickleyid/agent-builder-framework/tree/main/examples/${ex.template}`}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-sm text-accent-blue hover:text-accent-cyan transition-colors font-medium"
                      >
                        View Full Example →
                      </a>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>

          <div className="mt-12 text-center p-10 holographic-card rounded-xl border border-border hover:border-accent-blue/50 transition-all">
            <div className="w-20 h-20 rounded-2xl bg-gradient-to-br from-blue-600 to-indigo-600 flex items-center justify-center mx-auto mb-6 shadow-lg shadow-blue-500/30">
              <Sparkles className="w-10 h-10 text-white" />
            </div>
            <h3 className="text-3xl font-bold mb-4">Build Your Custom Agent</h3>
            <p className="text-zinc-400 mb-8 text-lg max-w-2xl mx-auto leading-relaxed">
              Ready to create something unique? Use our interactive CLI to scaffold and deploy your custom AI agent.
            </p>
            <pre className="bg-black/40 border border-border rounded-xl p-6 mb-8 inline-block text-left">
              <code className="text-accent-cyan terminal-text text-base">$ npm install -g @stick-ai/cli{'\n'}$ stick init my-agent{'\n'}$ stick deploy</code>
            </pre>
            <div className="flex gap-4 justify-center flex-wrap">
              <Link
                href="/docs/getting-started"
                className="px-8 py-4 bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 text-white rounded-xl font-semibold transition-all shadow-xl shadow-accent-blue/30 hover:scale-105"
              >
                Read Documentation
              </Link>
              <Link
                href="/playground"
                className="px-8 py-4 glass-morphic hover:bg-surface border border-white/20 text-white rounded-xl font-semibold transition-all hover:scale-105"
              >
                Try Visual Builder
              </Link>
            </div>
          </div>
        </div>
      </div>
    </main>
  );
}
