// my-agent - AI Agent
// Generated by stick.ai CLI

const { IntelligentAgent } = require('@stick-ai/runtime');

const config = require('./config/agent.json');

async function main() {
  
  // Create intelligent agent with ollama
  const agent = new IntelligentAgent(
    config,
    {
      provider: 'ollama',
      apiKey: process.env.OLLAMA_API_KEY,
      model: 'gpt-3.5-turbo',
      temperature: 0.7,
      maxTokens: 4000
    }
  );
  
  
  console.log('🤖 my-agent is running...');
  console.log('Tools:', config.tools.join(', '));
  
  // Example: Run agent with input
  // const result = await agent.run('Your task here');
  // console.log('Result:', result);
}

if (require.main === module) {
  main().catch(console.error);
}

module.exports = { main };
